#%RAML 0.8
---
title: Squawk API
baseUri: http://192.168.0.13:8080/api/
version: v1

/album:
  get:
    queryParameters:
        artist:
            displayName: Filter by artist.
            type: number
            description: Filter results by artist id.
            example: 0
            required: false
        name:
            displayName: Name
            type: string
            description: Searh for album titles.
            example: live
            required: false
        genre:
            displayName: Genre
            type: string
            description: Filter by genre.
            example: Pop
            required: false
        year:
            displayName: Year
            type: number
            description: Filter by year
            example: 2000
            required: false
        index:
            displayName: Index
            type: number
            description: Start index of the result items.
            example: 0
            required: false
        limit:
            displayName: Limit
            type: number
            description: Limit the number fo items returned.
            example: 10
            required: false
        attributes:
            displayName: Attributes
            type: string
            description: Include the attributes in the response {id, name, genre, year, artist}. When attributes is not set all the attributes will be returned.
            example: id,name
            required: false
        order:
            displayName: Order
            type: string
            description: The order of the results {name, insert, year}. default is name.
            example: name
            required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "count": 4168,
                "albums": [
                  {
                    "name": "Album 1",
                    "genre": "Pop",
                    "year": "2000",
                    "id": 1,
                    "artists": [
                      {
                        "id": 1,
                        "name": "Artist 1"
                      }
                    ]
                  },
                  {
                    "name": "Album 2",
                    "genre": "Jazz",
                    "year": "1986",
                    "id": 2,
                    "artists": [
                      {
                        "id": 2,
                        "name": "Artist 2"
                      }
                    ]
                  }
                ]
              }

  /{albumId}:
    description: Get album details by id.
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "name": "Album Name",
                  "genre": "Pop",
                  "year": "2014",
                  "id": 1,
                  "artists": [
                    {
                      "id": 1,
                      "name": "Artist 1"
                    }
                  ],
                  "songs": [
                    {
                      "id": 1,
                      "title": "Song Title 1",
                      "track": 1,
                      "filename": "/filename.flac",
                      "length": 330,
                      "bitrate": 0,
                      "samplerate": 44100,
                      "bps": 16,
                      "channels": 2,
                      "mimetype": "audio/x-flac",
                      "disc": 0
                    }
                    ],
                      "images": [
                        504,
                        505
                    ]
                }

    /cover.jpg:
      description: Get the album cover.
      get:
        responses:
          200:
            body:
              image/jpeg:

/artist:
  get:
    description: Get artist list.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "A": [
                  {
                    "id": 1,
                    "name": "Artist A"
                  }
                ],
                "B": [
                  {
                    "id": 2,
                    "name": "Artist B"
                  }
                ]
              }

/book:
  get:
    queryParameters:
        name:
            displayName: Name
            type: string
            description: Searh for album titles.
            example: live
            required: false
        index:
            displayName: Index
            type: number
            description: Start index of the result items.
            example: 0
            required: false
        limit:
            displayName: Limit
            type: number
            description: Limit the number fo items returned.
            example: 10
            required: false
        attributes:
            displayName: Attributes
            type: string
            description: Include the attributes in the response {id, name, genre, year, artist}. When attributes is not set all the attributes will be returned.
            example: id,name
            required: false
        order:
            displayName: Order
            type: string
            description: The order of the results {name, insert, year}. default is name.
            example: name
            required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "count": 2,
                "books": [
                  {
                    "name": "Album 1",
                    "genre": "Pop",
                    "year": "2000",
                    "id": 1,
                    "artists": [
                      {
                        "id": 1,
                        "name": "Artist 1"
                      }
                    ]
                  },
                  {
                    "name": "Album 2",
                    "genre": "Jazz",
                    "year": "1986",
                    "id": 2,
                    "artists": [
                      {
                        "id": 2,
                        "name": "Artist 2"
                      }
                    ]
                  }
                ]
              }

/resource:
  displayName: Resource
  get:
    responses:
      200:
        body:
          image/jpeg:

/statistic:
  get:
    description: Get media directory statistics.
    responses:
      200:
        body:
          application/json:
            example: |
              {
               "albums":4089,
               "artists":1217,
               "audiofiles":{
                 "audio/mpeg":3955,
                 "audio/x-flac":48013,
                 "audio/x-musepack":79,
                 "image/gif":1,
                 "image/jpeg":14261,
                 "image/png":5,
                 "video/mp4":6,
                 "video/x-matroska":2,
                 "video/x-msvideo":1
              },
                "types": {
                  "IMAGE": 14290,
                  "VIDEO": 9,
                  "AUDIO": 52066
                }
              }

/upnp/event:
  get:
    description: Get UPNP Event list.

/upnp/device:
  get:
    description: Get UPNP device list.

/video:
  get:
    description: Get Video list.
